- id: '1754414363475'
  alias: Uso prolungato condizionatore camera da letto
  description: Quando il condizionatore e' acceso da piu' di 3 ore, avvisa l'utente
  triggers:
  - entity_id:
    - climate.daikin_camera_da_letto
    to:
    for:
      hours: 3
      minutes: 0
      seconds: 0
    trigger: state
    from: 'off'
  conditions:
  - condition: time
    after: 08:00:00
    before: '23:00:00'
  actions:
  - action: notify.alexa_media_echo_dot_camera
    data:
      message: Il condizionatore e' acceso da piu' di tre ore
  mode: single
- id: '1754415850058'
  alias: Uso prolungato condizionatore salotto
  description: Quando il condizionatore e' acceso da piu' di 3 ore, avvisa l'utente
  triggers:
  - entity_id:
    - climate.daikin_salotto
    to:
    for:
      hours: 3
      minutes: 0
      seconds: 0
    trigger: state
    from: 'off'
  conditions:
  - condition: time
    after: 08:00:00
    before: '23:00:00'
  actions:
  - action: notify.alexa_media_echo_dot_salotto
    data:
      message: Il condizionatore e' acceso da piu' di tre ore
  mode: single
- id: '1754416382928'
  alias: Lavastoviglie fine programma
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.lavastoviglie_operation_state
    from: run
    to: finished
  conditions:
  - condition: time
    after: 08:00:00
    before: '23:50:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  actions:
  - action: notify.alexa_media_echo_dot_salotto
    metadata: {}
    data:
      message: La lavastoviglie ha finito
  mode: single
- id: '1757923183242'
  alias: Periodic speedtest
  description: ''
  triggers:
  - trigger: time_pattern
    hours: /8
  conditions: []
  actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - action: ookla_speedtest.run_speedtest
    metadata: {}
    data: {}
  mode: single
